### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'clear')

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [SDoehren/tension-pool#20] opened 2021-09-24 20:11 UTC
**Feedback Type**: Bug
 
**Core:** 0.8.9
**System:** dnd5e v1.4.3
**Module Version:** tension-pool v0052
**Dependency Version:** Dice So Nice! v4.1.5
**Dependency Version:** Library: Chat Commands v1.3.3
 
**Description**:
When running with the Perfect Vision Module, I receive the following error:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'clear')  PolyBuilder.ts:8  
    at Y.clear (PolyBuilder.ts:8)  
    at ControlIcon.draw (foundry.js:35392)<details>
<summary>Module Settings</summary>

```js
scenecontrols: true,
maxdiceinpool: 6,
emptythepool: false,
dropdie: true,
dicesize: dt,
outputto: notfications,
SafeMessage: You are safe for now.,
DangerMessage: <strong style='color:red'>Complication!</strong>,
PauseDuringRoll: true,
PauseOnComplication: true,
MacroName: ,
outputsum: false,
secsautodiceadd: 300
```
</details>
<details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by SDoehren** [comment] 2021-09-24 23:45
None of the modules mentioned use typescript so it is likely another module causing the error.  Unable to replicated via testing, closed awaiting further reports.

**Comment by dev7355608** [comment] 2021-10-31 13:40
This is not caused by Perfect Vision. I was able to reproduce it without it:

```
graphics.min.js:8 Uncaught (in promise) TypeError: Cannot read property 'clear' of null
    at r.clear (graphics.min.js:8)
    at ControlIcon.draw (foundry.js:35393)
```

Just Tension Pool + dependencies. If Tension Pool is disabled, the error message disappears as well.

The error only occurs if there's a note on the map. The TensionLayer is a Note document layer, which, when it is drawn, redraws all Note placeables. Before redrawing it clears the placeables: all contents including the control icons are destroyed. But the control icon is drawn async without await, so, I assume, it tries to draw the control icons after they are destroyed by the clear. The error message occurs, because `ControlIcon.bg` is already destroyed.

**Comment by SDoehren** [comment] 2021-10-31 14:13
Thanks.

It is the layer issue and will be resolved in the next release.

**Comment by SDoehren** [comment] 2021-11-21 22:48
V0055 has been released, this issue should be resolved.  Let me know if you have further issues.

**Closed as completed by SDoehren** 2021-11-21 22:48 UTC
Labels: bug, Implemented in Next Release
